http:
  port: ${PORT}
apiEndpoints:
  auth:
    host: '*'
    paths: ['/api/auth', '/api/auth/*']
  fighters:
    host: '*'
    paths: ['/api/fighters', '/api/fighters/*']
  events:
    host: '*'
    paths: ['/api/events', '/api/events/*']
  news:
    host: '*'
    paths: ['/api/news', '/api/news/*']
  predictions:
    host: '*'
    paths: ['/api/predictions', '/api/predictions/*']
serviceEndpoints:
  authService:
    url: ${AUTH_SERVICE_URL}
  fightersService:
    url: ${FIGHTERS_SERVICE_URL}
  eventsService:
    url: ${EVENTS_SERVICE_URL}
  newsService:
    url: ${NEWS_SERVICE_URL}
  predictionsService:
    url: ${PREDICTIONS_SERVICE_URL}
policies:
  - proxy
  - cors
  - log
pipelines:
  fightersPipeline:
    apiEndpoints: [fighters]
    policies:
      - log:
          - action:
              message: 'Proxying request to fightersService: ${req.url}'
      - cors:
          - action:
              origin: '*'
              methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'
      - proxy:
          - action:
              serviceEndpoint: fightersService
              changeOrigin: true
  authPipeline:
    apiEndpoints: [auth]
    policies:
      - log:
          - action:
              message: 'Proxying request to authService: ${req.url}'
      - cors:
          - action:
              origin: '*'
              methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
  eventsPipeline:
    apiEndpoints: [events]
    policies:
      - log:
          - action:
              message: 'Proxying request to eventsService: ${req.url}'
      - cors:
          - action:
              origin: '*'
              methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'
      - proxy:
          - action:
              serviceEndpoint: eventsService
              changeOrigin: true
  newsPipeline:
    apiEndpoints: [news]
    policies:
      - log:
          - action:
              message: 'Proxying request to newsService: ${req.url}'
      - cors:
          - action:
              origin: '*'
              methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'
      - proxy:
          - action:
              serviceEndpoint: newsService
              changeOrigin: true
  predictionsPipeline:
    apiEndpoints: [predictions]
    policies:
      - log:
          - action:
              message: 'Proxying request to predictionsService: ${req.url}'
      - cors:
          - action:
              origin: '*'
              methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'
      - proxy:
          - action:
              serviceEndpoint: predictionsService
              changeOrigin: true
